{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "operational-hub-api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operational-hub-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "operational-hub-api.selectorLabels" . | nindent 6 }}
{{- end }}
