{{- if .Values.secretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "operational-hub-api.name" . }}-spc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "operational-hub-api.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync,Sync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  provider: aws
  secretObjects:
    - secretName: {{ include "operational-hub-api.secretName" . }}
      type: Opaque
      data:
        {{- range $secretKey := .Values.secretsManager.keys }}
        - objectName: {{ $secretKey }}
          key: {{ $secretKey }}
        {{- end }}
  parameters:
    objects: |
      - objectName: "{{ .Values.secretsManager.awsSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range $secretKey := .Values.secretsManager.keys }}
          - path: {{ $secretKey }}
            objectAlias: {{ $secretKey }}
          {{- end }}
{{- end }}
