apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aiae-operational-hub-dev
  namespace: argocd
spec:
  destinations:
    - namespace: aiae-operational-hub-dev
      server: https://kubernetes.default.svc
  sourceRepos:
    - CHANGE_ME_HELM_REPO_URL
    - CHANGE_ME_HELM_VERSIONS_REPO_URL
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operational-hub-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aiae-operational-hub-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: aiae-operational-hub-dev
  sources:
    - repoURL: CHANGE_ME_HELM_REPO_URL
      targetRevision: dev
      path: charts/java-service
      helm:
        valueFiles:
          - $versions/operational-hub-api/values.yaml
          - $versions/operational-hub-api/images.yaml
    - repoURL: CHANGE_ME_HELM_VERSIONS_REPO_URL
      targetRevision: dev
      ref: versions
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
