apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.appProject }}-{{ .Values.env }}
  namespace: {{ .Values.const.argoNamespace }}
spec:
  destinations:
    - namespace: {{ .Values.destination.namespace }}
      server: {{ .Values.destination.server | quote }}
  sourceRepos:
    - {{ .Values.source.helmRepositoryUrl | quote }}
    - {{ .Values.source.versionsRepositoryUrl | quote }}
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appProject }}-{{ .Values.env }}-root
  namespace: {{ .Values.const.argoNamespace }}
  finalizers:
    - {{ .Values.const.finalizer }}
spec:
  project: {{ .Values.appProject }}-{{ .Values.env }}
  destination:
    namespace: {{ .Values.const.argoNamespace }}
    server: {{ .Values.destination.server | quote }}
  source:
    repoURL: {{ .Values.source.helmRepositoryUrl | quote }}
    targetRevision: {{ .Values.env }}
    path: aiae
    helm:
      parameters:
        - name: destination.server
          value: {{ .Values.destination.server | quote }}
        - name: source.helmRepositoryUrl
          value: {{ .Values.source.helmRepositoryUrl | quote }}
        - name: source.versionsRepositoryUrl
          value: {{ .Values.source.versionsRepositoryUrl | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
