env: dev
appProject: aiae
const:
  argoNamespace: argocd
  finalizer: resources-finalizer.argocd.argoproj.io
destination:
  server: ""
  namespace: aiae-dev
source:
  helmRepositoryUrl: ""
  versionsRepositoryUrl: ""
  chartRevision: "5480b8bca8d0562eba8a198170830c957b603eab"
  operationalHubVersionsRevision: "ed0521b9b36ac6af7cfe17a048e870b4c8105973"
services:
  operationalHubApi:
    enabled: true
    imageRepository: 496336474487.dkr.ecr.us-east-1.amazonaws.com/aidigital.aiae-projects/operational-hub-application
    liquibaseImageRepository: 496336474487.dkr.ecr.us-east-1.amazonaws.com/aidigital.aiae-projects/operational-hub-application
    iamRoleArn: arn:aws:iam::496336474487:role/aiae-operational-hub-dev-application
    secretName: AIAE-DEV/operational-hub
    host: ""
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 1
    config:
      SPRING_PROFILES_ACTIVE: eks
      PORT: "5000"
      MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
      AUTH_ALLOWED_EMAIL_DOMAIN: aidigital.com
      AUTH_AUTHORIZED_PARTIES: "https://dfjozbcz9mj59.cloudfront.net"
      OPH_SECURITY_CORS_ALLOWED_ORIGINS: "https://dfjozbcz9mj59.cloudfront.net"
      OPH_SECURITY_CSP_FRAME_ANCESTORS: "'self' https://dfjozbcz9mj59.cloudfront.net"
      BIGQUERY_ENABLED: "true"
      BIGQUERY_PROJECT_ID: aiae-493511
      BIGQUERY_STUB_ENABLED: "false"
      BIGQUERY_LOCATION: US
      BIGQUERY_DATASET: netsuite
      USAGE_LOG_ENVIRONMENT: dev
