env: dev
appProject: aiae-operational-hub
const:
  argoNamespace: argocd
  finalizer: resources-finalizer.argocd.argoproj.io
destination:
  server: ""
  namespace: aiae-operational-hub-dev
source:
  helmRepositoryUrl: ""
  versionsRepositoryUrl: ""
  chartRevision: "aabe377a87d6fc90fec33a17d07b2dd7d0c473e8"
  operationalHubVersionsRevision: "59b50aabfb0403190f64781650b957830a3b5341"
services:
  operationalHubApi:
    enabled: true
    imageRepository: 496336474487.dkr.ecr.us-east-1.amazonaws.com/aidigital.aiae-projects/operational-hub-application
    liquibaseImageRepository: 496336474487.dkr.ecr.us-east-1.amazonaws.com/aidigital.aiae-projects/operational-hub-application
    iamRoleArn: arn:aws:iam::496336474487:role/aiae-operational-hub-dev-application
    secretName: AIAE-DEV/operational-hub
    host: dev.aiae-operational-hub.aidigital.tech
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 1
    config:
      SPRING_PROFILES_ACTIVE: eks
      PORT: "5000"
      MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
      AUTH_ALLOWED_EMAIL_DOMAIN: aidigital.com
      AUTH_AUTHORIZED_PARTIES: "https://1fae4737-1001-4c87-b86a-e6c8de2a96a0-00-vkdhsp6p2d5t.kirk.replit.dev,http://localhost:5173,http://localhost:5000,https://1fae4737-1001-4c87-b86a-e6c8de2a96a0-00-vkdhsp6p2d5t.kirk.replit.dev:5173,https://dev.aiae-operational-hub.aidigital.tech"
      CLERK_PUBLISHABLE_KEY: pk_test_bGl2aW5nLWluc2VjdC02MC5jbGVyay5hY2NvdW50cy5kZXYk
      OPH_SECURITY_CORS_ALLOWED_ORIGINS: "https://1fae4737-1001-4c87-b86a-e6c8de2a96a0-00-vkdhsp6p2d5t.kirk.replit.dev,http://localhost:5173,http://localhost:5000,https://1fae4737-1001-4c87-b86a-e6c8de2a96a0-00-vkdhsp6p2d5t.kirk.replit.dev:5173,https://dev.aiae-operational-hub.aidigital.tech"
      OPH_SECURITY_CSP_FRAME_ANCESTORS: "'self' https://*.replit.dev https://dev.aiae-operational-hub.aidigital.tech"
      BIGQUERY_ENABLED: "true"
      BIGQUERY_PROJECT_ID: aiae-493511
      BIGQUERY_STUB_ENABLED: "false"
      BIGQUERY_LOCATION: US
      BIGQUERY_DATASET: netsuite
      USAGE_LOG_ENVIRONMENT: dev
      LOGBOOK_LEVEL: INFO
